import TenStackProvider from "@/provider/TenstackProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

import ReduxProvider from "@/provider/ReduxProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <TenStackProvider>
          {/*  NavBar*/}
          <Navbar />
          <nav>
            <h1>Navbar ho hai</h1>
          </nav>

          <body className={inter.className}> {children}</body>
        </TenStackProvider>
      </ReduxProvider>
    </html>
  );
}
