import { Inter } from "next/font/google";
import type { Metadata } from "next";
import TenStackProvider from "@/provider/TenstackProvider";
import Navbar from "@/components/Navbar";

import ReduxProvider from "@/provider/ReduxProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <TenStackProvider>
          {/*  NavBar*/}
          <nav>
            <Navbar />
          </nav>

          <body className={`${inter.className}`}> {children}</body>
        </TenStackProvider>
      </ReduxProvider>
    </html>
  );
}
